### ISSUE TITLE
wallet: "Options" menu item in GUI placed differently on Windows and Mac

### ISSUE THREAD

**Issue by rocketsvm** [Raptor3um/raptoreum-docs#46]
At least two Mac users (me included, but I was using it for 15 minutes) were unable to find "Options" menu item under "Settings" on Mac from the first run.

It's location on Windows: 
![win-settings](https://user-images.githubusercontent.com/1271217/200403485-f3467c76-50bc-4e93-9c54-60e4dd1b8a4e.png)

But it's missing on Mac:
<img width="245" alt="mac-settings" src="https://user-images.githubusercontent.com/1271217/200403599-030e6dfa-dbd5-4866-9287-235aa3e4efcc.png">

On Mac it is actually here, and called "Preferences" in this case:
![mac-main](https://user-images.githubusercontent.com/1271217/200403805-5dbf4fe5-d60e-4aa1-93a5-fd0e09e3beb9.png)

**Comment by HumbleDeer** [comment]
Thank you for reporting on this 🙂 

I will see about adding a temporary notice to the docs, and check with devs whether this can be fixed in the codebase of the wallet.

**Comment by HumbleDeer** [comment]
@npq7721 Is this possibly a bug in the Qt layout for Mac? 

I've not had the time to go through the repo for RaptoreumCore, so haven't found anything myself yet. If anyone else is more appropriate to go over Qt framework things, please do tag!

**Comment by rocketsvm** [comment]
Pull request with possible fix [submitted](https://github.com/Raptor3um/raptoreum/pull/251).

**Comment by HumbleDeer** [comment]
Thank you!
