### ISSUE TITLE
Add warning about encrypted drives!

### ISSUE THREAD

**Issue by Bigpiggy01** [Raptor3um/raptoreum-docs#47]
Encrypted drive partitions may in some cases damage or alter wallet.dat files.
Particular known miscreants are VeraCrypt and AxCrypt however we can not rule out other drive encryption options may do the same!
If you run an encrypted wallet from an encrypted partition you should in most cases be fine as both encrypt the actual file.
Problems may occur if running with an unencrypted wallet.dat from an encrypted drive partition as the way it is written to disk may cause the wallet to be mistaken for an encrypted wallet by the wallet software should it be used to restore the wallet on an unencrypted machine!
**STRONGLY ADVISE** running the HD wallet only with encrypted drives! Include link to HD guide!

**Comment by Bigpiggy01** [comment]
Just add a warning saying use HD wallet only if running encrypted drive partitions!

**Comment by HumbleDeer** [comment]
Okay. I'll see what I can do. 

Is there anywhere I can read up on why this is, what happens if you don't, etcetera? I'd like to be more verbose than "Only use the HD-wallet if you're running an encrypted drive". Is it a matter of sticking with either unencrypted or encrypted but not moving wallets across from one to the other?

**Comment by Bigpiggy01** [comment]
Bitcointalk the really old troubleshooting threads!
It boils down to the wallet physically encrypting the file which changes how it is written to disk. Some encryption software for partitions will make the same changes. So if you have an unencrypted wallet.dat from an encrypted partition this may confuse the wallet software later making it think it is encrypted.
